!  This file was generated by kmcos (kinetic Monte Carlo of Systems)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Tomoyuki TSUYAMA.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmcos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist_constants
use kind_values
use lattice, only: &
    ru_slab, &
    ru_slab_p1, &
    ru_slab_p2, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 4
integer(kind=iint), parameter, public :: at = 0
integer(kind=iint), parameter, public :: empty = 1
integer(kind=iint), parameter, public :: rn = 2
integer(kind=iint), parameter, public :: ru = 3
integer(kind=iint), public :: default_species = empty

! Process constants

integer(kind=iint), parameter, public :: ru_interaction_0 = 1
integer(kind=iint), parameter, public :: ru_interaction_1 = 2
integer(kind=iint), parameter, public :: ru_interaction_10 = 3
integer(kind=iint), parameter, public :: ru_interaction_11 = 4
integer(kind=iint), parameter, public :: ru_interaction_12 = 5
integer(kind=iint), parameter, public :: ru_interaction_13 = 6
integer(kind=iint), parameter, public :: ru_interaction_14 = 7
integer(kind=iint), parameter, public :: ru_interaction_15 = 8
integer(kind=iint), parameter, public :: ru_interaction_16 = 9
integer(kind=iint), parameter, public :: ru_interaction_17 = 10
integer(kind=iint), parameter, public :: ru_interaction_18 = 11
integer(kind=iint), parameter, public :: ru_interaction_19 = 12
integer(kind=iint), parameter, public :: ru_interaction_2 = 13
integer(kind=iint), parameter, public :: ru_interaction_20 = 14
integer(kind=iint), parameter, public :: ru_interaction_21 = 15
integer(kind=iint), parameter, public :: ru_interaction_22 = 16
integer(kind=iint), parameter, public :: ru_interaction_23 = 17
integer(kind=iint), parameter, public :: ru_interaction_3 = 18
integer(kind=iint), parameter, public :: ru_interaction_4 = 19
integer(kind=iint), parameter, public :: ru_interaction_5 = 20
integer(kind=iint), parameter, public :: ru_interaction_6 = 21
integer(kind=iint), parameter, public :: ru_interaction_7 = 22
integer(kind=iint), parameter, public :: ru_interaction_8 = 23
integer(kind=iint), parameter, public :: ru_interaction_9 = 24

end module proclist_constants
