!  This file was generated by kmcos (kinetic Monte Carlo of Systems)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Tomoyuki TSUYAMA.

!  This file is part of kmcos.
!
!  kmcos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmcos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmcos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
module proclist_pars
use kind_values
use base, only: &
    rates
use proclist_constants
use lattice, only: &
    fept, &
    fept_origin, &
    get_species

implicit none

! User parameters
integer(kind=iint), public :: J_NN = 1
integer(kind=iint), public :: J_NNN = 2
integer(kind=iint), public :: T = 3
real(kind=rdouble), public, dimension(3) :: userpar

! Constants
real(kind=rdouble), parameter :: eV = 1.6021765650e-19
real(kind=rdouble), parameter :: kboltzmann = 1.3806488000e-23

! Species masses
character(len=103), parameter, public :: byst_FePt_interaction_0 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_1 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_10 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_11 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_2 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_3 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_4 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_5 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_6 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_7 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_8 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"
character(len=103), parameter, public :: byst_FePt_interaction_9 = "nr_fe_nnbase &
    &nr_pt_nnbase &
    &nr_fe_nnnbase &
    &nr_pt_nnnbase &
    &nr_fe_nnnori &
    &nr_pt_nnnori &
    &nr_fe_nnori &
    &nr_pt_nnori"

contains
subroutine update_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(in) :: val
    userpar(param) = val
end subroutine update_user_parameter

subroutine get_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(out) :: val
    val = userpar(param)
end subroutine get_user_parameter


function gr_FePt_interaction_0(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_0

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, -2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -2, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-2, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -3, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -1, -3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/2, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_0 = rate_FePt_interaction_0(nr_vars)
    return

end function gr_FePt_interaction_0

function rate_FePt_interaction_0(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_0
    rate_FePt_interaction_0 = rates (FePt_interaction_0 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_0


function gr_FePt_interaction_1(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_1

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-2, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-3, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, -2, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 0, -3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 2, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_1 = rate_FePt_interaction_1(nr_vars)
    return

end function gr_FePt_interaction_1

function rate_FePt_interaction_1(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_1
    rate_FePt_interaction_1 = rates (FePt_interaction_1 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_1


function gr_FePt_interaction_10(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_10

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -2, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 2, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/3, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_10 = rate_FePt_interaction_10(nr_vars)
    return

end function gr_FePt_interaction_10

function rate_FePt_interaction_10(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_10
    rate_FePt_interaction_10 = rates (FePt_interaction_10 ) * min (&
    &1.00  , exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) &
    &*  2 * (nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) &
    &)  ) + userpar(J_NNN) * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_10


function gr_FePt_interaction_11(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_11

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 1, -2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 1, 2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 3, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/3, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_11 = rate_FePt_interaction_11(nr_vars)
    return

end function gr_FePt_interaction_11

function rate_FePt_interaction_11(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_11
    rate_FePt_interaction_11 = rates (FePt_interaction_11 ) * min (&
    &1.00  , exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) &
    &*  2 * (nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) &
    &)  ) + userpar(J_NNN) * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_11


function gr_FePt_interaction_2(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_2

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-2, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-3, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, -3, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, -1, -2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, -1, 2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_2 = rate_FePt_interaction_2(nr_vars)
    return

end function gr_FePt_interaction_2

function rate_FePt_interaction_2(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_2
    rate_FePt_interaction_2 = rates (FePt_interaction_2 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_2


function gr_FePt_interaction_3(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_3

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, -2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -2, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-2, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -3, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -1, 3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/2, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_3 = rate_FePt_interaction_3(nr_vars)
    return

end function gr_FePt_interaction_3

function rate_FePt_interaction_3(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_3
    rate_FePt_interaction_3 = rates (FePt_interaction_3 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_3


function gr_FePt_interaction_4(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_4

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -2, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, -3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 2, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/3, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_4 = rate_FePt_interaction_4(nr_vars)
    return

end function gr_FePt_interaction_4

function rate_FePt_interaction_4(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_4
    rate_FePt_interaction_4 = rates (FePt_interaction_4 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_4


function gr_FePt_interaction_5(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_5

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-3, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 1, -2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 1, 2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 3, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_5 = rate_FePt_interaction_5(nr_vars)
    return

end function gr_FePt_interaction_5

function rate_FePt_interaction_5(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_5
    rate_FePt_interaction_5 = rates (FePt_interaction_5 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_5


function gr_FePt_interaction_6(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_6

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 2, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, -2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-2, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 1, -3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 3, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/2, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_6 = rate_FePt_interaction_6(nr_vars)
    return

end function gr_FePt_interaction_6

function rate_FePt_interaction_6(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_6
    rate_FePt_interaction_6 = rates (FePt_interaction_6 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_6


function gr_FePt_interaction_7(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_7

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-2, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, -1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-3, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, -2, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 0, 3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 2, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_7 = rate_FePt_interaction_7(nr_vars)
    return

end function gr_FePt_interaction_7

function rate_FePt_interaction_7(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_7
    rate_FePt_interaction_7 = rates (FePt_interaction_7 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_7


function gr_FePt_interaction_8(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_8

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -2, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, -2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -3, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -1, -2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, -1, 2, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/3, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_8 = rate_FePt_interaction_8(nr_vars)
    return

end function gr_FePt_interaction_8

function rate_FePt_interaction_8(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_8
    rate_FePt_interaction_8 = rates (FePt_interaction_8 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_8


function gr_FePt_interaction_9(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_FePt_interaction_9

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, -1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, -1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(7) = nr_vars(7) + 1
        case(pt)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/0, 2, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, 0, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 1, 2, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 2, 1, fept_origin/)))
        case(fe)
            nr_vars(1) = nr_vars(1) + 1
        case(pt)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, -2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, -2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 2, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 2, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, fept_origin/)))
        case(fe)
            nr_vars(5) = nr_vars(5) + 1
        case(pt)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-2, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, -1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 1, -1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 1, 3, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 3, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/2, 1, 1, fept_origin/)))
        case(fe)
            nr_vars(3) = nr_vars(3) + 1
        case(pt)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_FePt_interaction_9 = rate_FePt_interaction_9(nr_vars)
    return

end function gr_FePt_interaction_9

function rate_FePt_interaction_9(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_FePt_interaction_9
    rate_FePt_interaction_9 = rates (FePt_interaction_9 ) * min (1.00 &
    &,  exp ((1 / (kboltzmann * userpar(T) ) ) * (userpar(J_NN) * 2 * &
    &( nr_vars(7) - nr_vars(8) - (nr_vars(1) - nr_vars(2) ) ) + &
    &userpar(J_NNN)  * 2 * (nr_vars(5) - nr_vars(6) - (&
    &nr_vars(3)  - nr_vars(4) ) ) ) * eV ) )   

    return

end function rate_FePt_interaction_9


end module proclist_pars
